"""empty message

Revision ID: 374bd75cf142
Revises: 81689562631d
Create Date: 2017-11-22 19:11:00.985877

"""

# revision identifiers, used by Alembic.
revision = '374bd75cf142'
down_revision = '81689562631d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entities', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'entities', 'user', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'updated_by_id')
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'created_by_id')
    op.drop_column('entities', 'created_at')
    # ### end Alembic commands ###
