"""empty message

Revision ID: 39b09b7019e4
Revises: d9673131a393
Create Date: 2017-11-15 17:25:15.220666

"""

# revision identifiers, used by Alembic.
revision = '39b09b7019e4'
down_revision = 'd9673131a393'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('wiki_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'wiki_link')
    # ### end Alembic commands ###
