"""empty message

Revision ID: 452e194acb07
Revises: e8d48737233d
Create Date: 2017-11-05 16:34:09.331799

"""

# revision identifiers, used by Alembic.
revision = '452e194acb07'
down_revision = 'e8d48737233d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('wiki_page_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'wiki_page_id')
    # ### end Alembic commands ###
