"""empty message

Revision ID: 66b9ee4f8be5
Revises: e89758723513
Create Date: 2017-12-06 15:36:06.177216

"""

# revision identifiers, used by Alembic.
revision = '66b9ee4f8be5'
down_revision = 'e89758723513'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verified_email')
    # ### end Alembic commands ###
