"""empty message

Revision ID: 71e75237227b
Revises: c39d71c733b2
Create Date: 2017-11-10 16:22:13.659502

"""

# revision identifiers, used by Alembic.
revision = '71e75237227b'
down_revision = 'c39d71c733b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_on')
    # ### end Alembic commands ###
