"""empty message

Revision ID: 81689562631d
Revises: 78b6eab1a1a1
Create Date: 2017-11-15 18:05:02.318544

"""

# revision identifiers, used by Alembic.
revision = '81689562631d'
down_revision = '78b6eab1a1a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'wiki_page_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('wiki_page_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
