"""empty message

Revision ID: 9d2828aa95a0
Revises: 452e194acb07
Create Date: 2017-11-08 12:54:00.270559

"""

# revision identifiers, used by Alembic.
revision = '9d2828aa95a0'
down_revision = '452e194acb07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_meta_data')
    # ### end Alembic commands ###
