"""empty message

Revision ID: a55539b1f994
Revises: a9b03b297aa1
Create Date: 2017-12-06 17:23:27.846825

"""

# revision identifiers, used by Alembic.
revision = 'a55539b1f994'
down_revision = 'a9b03b297aa1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verified_email', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verified_email', 'created_at')
    # ### end Alembic commands ###
