"""empty message

Revision ID: a9b03b297aa1
Revises: 66b9ee4f8be5
Create Date: 2017-12-06 15:52:26.085530

"""

# revision identifiers, used by Alembic.
revision = 'a9b03b297aa1'
down_revision = '66b9ee4f8be5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
