"""empty message

Revision ID: e89758723513
Revises: 9f91e1cd8655
Create Date: 2017-11-28 16:41:37.254954

"""

# revision identifiers, used by Alembic.
revision = 'e89758723513'
down_revision = '9f91e1cd8655'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('blacklist', sa.Boolean(), nullable=True))
    op.add_column('entities', sa.Column('blacklist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'blacklist')
    op.drop_column('edges', 'blacklist')
    # ### end Alembic commands ###
