"""empty message

Revision ID: eeaecdef3319
Revises: ef8776163ea8
Create Date: 2017-12-15 08:30:49.275308

"""

# revision identifiers, used by Alembic.
revision = 'eeaecdef3319'
down_revision = 'ef8776163ea8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
