"""empty message

Revision ID: ef8776163ea8
Revises: a55539b1f994
Create Date: 2017-12-07 11:20:24.510785

"""

# revision identifiers, used by Alembic.
revision = 'ef8776163ea8'
down_revision = 'a55539b1f994'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('candidate', sa.Boolean(), nullable=True))
    op.add_column('entities', sa.Column('candidate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'candidate')
    op.drop_column('edges', 'candidate')
    # ### end Alembic commands ###
